pipeline {
    agent any 
    environment {
        TEST_FLAG = 'true'
        TEST_NAME = 'Ethan'
    }
    stages {
        stage('Stage 1') {
            steps {
                sh 'Jenkins Version 1.1'
            }
        }

        stage('Stage 2') {
            steps {
                echo 'Hello world!' 
            }
        }
    }
    post {
        always {
            echo 'One way or another, I have finished'
            deleteDir() /* clean up our workspace */
        }
        success {
            echo 'I succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things were different before...'
        }
    }
}